"""explicitely say to set null to hero row when the team is deleted

Revision ID: 9eb98bf81aa9
Revises: b2a4133a0ef1
Create Date: 2026-05-03 05:59:11.163893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9eb98bf81aa9'
down_revision: Union[str, Sequence[str], None] = 'b2a4133a0ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hero_data_team_id_fkey'), 'hero_data', type_='foreignkey')
    op.create_foreign_key(None, 'hero_data', 'team_data', ['team_id'], ['id_'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero_data', type_='foreignkey')
    op.create_foreign_key(op.f('hero_data_team_id_fkey'), 'hero_data', 'team_data', ['team_id'], ['id_'], ondelete='CASCADE')
    # ### end Alembic commands ###
