"""add cascade delete to hero_data.team_id

Revision ID: b2a4133a0ef1
Revises: b9eeabcc9338
Create Date: 2026-05-03 00:17:28.029350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b2a4133a0ef1'
down_revision: Union[str, Sequence[str], None] = 'b9eeabcc9338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hero_data_team_id_fkey'), 'hero_data', type_='foreignkey')
    op.create_foreign_key(None, 'hero_data', 'team_data', ['team_id'], ['id_'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero_data', type_='foreignkey')
    op.create_foreign_key(op.f('hero_data_team_id_fkey'), 'hero_data', 'team_data', ['team_id'], ['id_'])
    # ### end Alembic commands ###
