"""add team class with the relationship with hero

Revision ID: b9eeabcc9338
Revises: f0100f21331c
Create Date: 2026-05-02 10:04:54.656676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b9eeabcc9338'
down_revision: Union[str, Sequence[str], None] = 'f0100f21331c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_data',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headquarters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_')
    )
    op.add_column('hero_data', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hero_data', 'team_data', ['team_id'], ['id_'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero_data', type_='foreignkey')
    op.drop_column('hero_data', 'team_id')
    op.drop_table('team_data')
    # ### end Alembic commands ###
