"""add restric to that delete the team not will delte teh hero in the sql

Revision ID: ec5faa8ab70e
Revises: 9eb98bf81aa9
Create Date: 2026-05-03 06:15:36.287347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ec5faa8ab70e'
down_revision: Union[str, Sequence[str], None] = '9eb98bf81aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hero_data_team_id_fkey'), 'hero_data', type_='foreignkey')
    op.create_foreign_key(None, 'hero_data', 'team_data', ['team_id'], ['id_'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero_data', type_='foreignkey')
    op.create_foreign_key(op.f('hero_data_team_id_fkey'), 'hero_data', 'team_data', ['team_id'], ['id_'], ondelete='SET NULL')
    # ### end Alembic commands ###
