"""add phone number in hero table

Revision ID: f0100f21331c
Revises: 5cb9fdf1bb98
Create Date: 2026-05-02 06:23:58.539589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f0100f21331c'
down_revision: Union[str, Sequence[str], None] = '5cb9fdf1bb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero_data', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero_data', 'phone')
    # ### end Alembic commands ###
